---

- name: Install required software
  win_chocolatey:
    name: "{{ item }}"
  loop: "{{ choco_list }}"

- name: copy ssh keys
  win_copy:
    src: "/home/{{ lin_username }}/.ssh/"
    dest: "C:\\Users\\{{ win_username }}\\.ssh"

- name: copy gitconfig
  win_copy:
    src: "/home/{{ lin_username }}/.gitconfig"
    dest: "C:\\Users\\{{ username }}\\"
