---

- name: run the playbook tasks on the localhost
  hosts: localhost
  connection: local
  become: yes
  vars:
    username: jaels
    git_fullname: "Yurii Fisakov"
    git_email: "fisakov.root@gmail.com"
    users:
      - username: "{{ username }}"
    ntp_timezone: Europe/Kiev


  roles:
    - geerlingguy.ntp
    - andrewrothstein.kubernetes-helm
    - guest
    - geerlingguy.docker
    - andrewrothstein.docker-machine
    - gantsign.oh-my-zsh 
    - andrewrothstein.go
