---
- name: install software
  apt:
    name: "{{ item }}"
  loop:
    - "{{ deps_list }}"
    - "{{ install_list }}"

- name: install ruby gems
  gem:
    name: "{{ item }}"
  loop: "{{ gem_list }}"

- name: python modules
  pip:
    name: "{{ item.name }}"
  loop: "{{ pip_install_packages }}"
